export const projects = [
  {
    title: 'CinemaHub',
    description: "CinemaHub is a movie database application built to share detailed information about any movie. The user can filter through categories to seek information about a variety of movies. The user can click on a movie, and it shows a summary of the movie, the actors involved, the trailer, and ability to comment the user's thoughts.",
      image: '/images/cinemahub.png',
      tags: ['React', 'Express', 'JavaScript', 'Node'],
    source: 'https://cinemahub.netlify.app/',
    visit: 'https://github.com/steventejeda/cinemahub',
    id: 0,
  },
  {
    title: 'Pathfinding Visualizer',
    description:"At its core, a pathfinding algorithm seeks to find the shortest path between two points. This application visualizes the A* Search Algorithm and I plan on implementing more algorithms as I continue to learn them at a deeper understanding.",
    image: '/images/pf.png',
    tags: ['React', 'JavaScript', 'CSS'],
    source: 'https://pathfinding-hodgkin-14bb43.netlify.app/',
    visit: 'https://github.com/steventejeda/pathfinding-visualizer',
    id: 1,
  },
  {
    title: 'Cryptocurrency Price Tracker',
    description: "Simple and clean crypto currency tracker built using React.js, JavaScript & CSS3. Utilizing the coingecko API to search for your favorite coins!",
      image: '/images/crypto.png',
      tags: ['React', 'JavaScript', 'CSS'],
    source: 'https://crypto-00202.netlify.app/',
    visit: 'https://github.com/steventejeda/cryptocurrencytracker',
    id: 2,
  },
  {
    title: 'React-Pokedex',
    description: "This app uses the Pokemon API to generate different types of pokemon and displays their stats. You can click on the PokemonCard components and they are flipped over using a custom hook called useFlip. You can add and delete pokemon",
    image: '/images/react-pokedex.png',
    tags: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'https://epic-borg-b84437.netlify.app/',
    visit: 'https://github.com/steventejeda/Pokedex_React/tree/main/pokedex_app',
    id: 3,
  },
  {
    title: 'Expense Tracker',
    description: "App was built using HTML, CSS, JavaScript along with React Hooks and Context API. Keep track of income and expenses. Add and remove transactions and save to local storage!",
    image: '/images/expense.png',
    tags: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'https://wonderful-beaver-8ebd66.netlify.app/',
    visit: 'https://github.com/steventejeda/expense-tracker',
    id: 4,
  },
  {
    title: 'React Movie App',
    description: "You can browse movies by searching for titles. If you hover over with your mouse an overview will slide up and have a brief synopsis about the movie. The API has 10's of thousands movie titles you can browse from.",
    image: '/images/movie.jpeg',
    tags: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'https://wonderful-beaver-8ebd66.netlify.app/',
    visit: 'https://github.com/steventejeda/expense-tracker',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Enrolled in Springboards Software Engineering Career Track', },
  { year: 2021, text: 'Graduated with a Certificate of completion. Currently building projects and solving dymanic problems.', },
];